In [1]:
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os 

load_dotenv('../.env')
engine = create_engine(
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)
print("Connected to database")

Connected to database

In [2]:
import sqlalchemy as sa

inspector = sa.inspect(engine)
tables = inspector.get_table_names()
print(tables)

['circuits', 'races', 'race_results', 'drivers', 'constructors', 'qualifying_results', 'weather', 'tyre_stints']

In [3]:
with engine.connect() as connection:
    result = connection.execute(sa.text("SELECT * FROM races"))
    for row in result:
        print(row)

(1, 'Sakhir', 2022, 1, datetime.date(2022, 3, 20))
(2, 'Jeddah', 2022, 2, datetime.date(2022, 3, 27))
(3, 'Melbourne', 2022, 3, datetime.date(2022, 4, 10))
(4, 'Imola', 2022, 4, datetime.date(2022, 4, 24))
(5, 'Miami', 2022, 5, datetime.date(2022, 5, 8))
(6, 'Barcelona', 2022, 6, datetime.date(2022, 5, 22))
(7, 'Monaco', 2022, 7, datetime.date(2022, 5, 29))
(8, 'Baku', 2022, 8, datetime.date(2022, 6, 12))
(9, 'Montréal', 2022, 9, datetime.date(2022, 6, 19))
(10, 'Silverstone', 2022, 10, datetime.date(2022, 7, 3))
(11, 'Spielberg', 2022, 11, datetime.date(2022, 7, 10))
(12, 'Le Castellet', 2022, 12, datetime.date(2022, 7, 24))
(13, 'Budapest', 2022, 13, datetime.date(2022, 7, 31))
(14, 'Spa-Francorchamps', 2022, 14, datetime.date(2022, 8, 28))
(15, 'Zandvoort', 2022, 15, datetime.date(2022, 9, 4))
(16, 'Monza', 2022, 16, datetime.date(2022, 9, 11))
(17, 'Marina Bay', 2022, 17, datetime.date(2022, 10, 2))
(18, 'Suzuka', 2022, 18, datetime.date(2022, 10, 9))
(19, 'Austin', 2022, 19, datetime.date(2022, 10, 23))
(20, 'Mexico City', 2022, 20, datetime.date(2022, 10, 30))
(21, 'São Paulo', 2022, 21, datetime.date(2022, 11, 13))
(22, 'Yas Island', 2022, 22, datetime.date(2022, 11, 20))
(23, 'Sakhir', 2023, 1, datetime.date(2023, 3, 5))
(24, 'Jeddah', 2023, 2, datetime.date(2023, 3, 19))
(25, 'Melbourne', 2023, 3, datetime.date(2023, 4, 2))
(26, 'Baku', 2023, 4, datetime.date(2023, 4, 30))
(27, 'Miami', 2023, 5, datetime.date(2023, 5, 7))
(28, 'Monaco', 2023, 6, datetime.date(2023, 5, 28))
(29, 'Barcelona', 2023, 7, datetime.date(2023, 6, 4))
(30, 'Montréal', 2023, 8, datetime.date(2023, 6, 18))
(31, 'Spielberg', 2023, 9, datetime.date(2023, 7, 2))
(32, 'Silverstone', 2023, 10, datetime.date(2023, 7, 9))
(33, 'Budapest', 2023, 11, datetime.date(2023, 7, 23))
(34, 'Spa-Francorchamps', 2023, 12, datetime.date(2023, 7, 30))
(35, 'Zandvoort', 2023, 13, datetime.date(2023, 8, 27))
(36, 'Monza', 2023, 14, datetime.date(2023, 9, 3))
(37, 'Marina Bay', 2023, 15, datetime.date(2023, 9, 17))
(38, 'Suzuka', 2023, 16, datetime.date(2023, 9, 24))
(39, 'Lusail', 2023, 17, datetime.date(2023, 10, 8))
(40, 'Austin', 2023, 18, datetime.date(2023, 10, 22))
(41, 'Mexico City', 2023, 19, datetime.date(2023, 10, 29))
(42, 'São Paulo', 2023, 20, datetime.date(2023, 11, 5))
(43, 'Las Vegas', 2023, 21, datetime.date(2023, 11, 18))
(44, 'Yas Island', 2023, 22, datetime.date(2023, 11, 26))
(45, 'Sakhir', 2024, 1, datetime.date(2024, 3, 2))
(46, 'Jeddah', 2024, 2, datetime.date(2024, 3, 9))
(47, 'Melbourne', 2024, 3, datetime.date(2024, 3, 24))
(48, 'Suzuka', 2024, 4, datetime.date(2024, 4, 7))
(49, 'Shanghai', 2024, 5, datetime.date(2024, 4, 21))
(50, 'Miami', 2024, 6, datetime.date(2024, 5, 5))
(51, 'Imola', 2024, 7, datetime.date(2024, 5, 19))
(52, 'Monaco', 2024, 8, datetime.date(2024, 5, 26))
(53, 'Montréal', 2024, 9, datetime.date(2024, 6, 9))
(54, 'Barcelona', 2024, 10, datetime.date(2024, 6, 23))
(55, 'Spielberg', 2024, 11, datetime.date(2024, 6, 30))
(56, 'Silverstone', 2024, 12, datetime.date(2024, 7, 7))
(57, 'Budapest', 2024, 13, datetime.date(2024, 7, 21))
(58, 'Spa-Francorchamps', 2024, 14, datetime.date(2024, 7, 28))
(59, 'Zandvoort', 2024, 15, datetime.date(2024, 8, 25))
(60, 'Monza', 2024, 16, datetime.date(2024, 9, 1))
(61, 'Baku', 2024, 17, datetime.date(2024, 9, 15))
(62, 'Marina Bay', 2024, 18, datetime.date(2024, 9, 22))
(63, 'Austin', 2024, 19, datetime.date(2024, 10, 20))
(64, 'Mexico City', 2024, 20, datetime.date(2024, 10, 27))
(65, 'São Paulo', 2024, 21, datetime.date(2024, 11, 3))
(66, 'Las Vegas', 2024, 22, datetime.date(2024, 11, 23))
(67, 'Lusail', 2024, 23, datetime.date(2024, 12, 1))
(68, 'Yas Island', 2024, 24, datetime.date(2024, 12, 8))
(69, 'Melbourne', 2025, 1, datetime.date(2025, 3, 16))
(70, 'Shanghai', 2025, 2, datetime.date(2025, 3, 23))
(71, 'Suzuka', 2025, 3, datetime.date(2025, 4, 6))
(72, 'Sakhir', 2025, 4, datetime.date(2025, 4, 13))
(73, 'Jeddah', 2025, 5, datetime.date(2025, 4, 20))
(74, 'Miami Gardens', 2025, 6, datetime.date(2025, 5, 4))
(75, 'Imola', 2025, 7, datetime.date(2025, 5, 18))
(76, 'Monaco', 2025, 8, datetime.date(2025, 5, 25))
(77, 'Barcelona', 2025, 9, datetime.date(2025, 6, 1))
(78, 'Montréal', 2025, 10, datetime.date(2025, 6, 15))
(79, 'Spielberg', 2025, 11, datetime.date(2025, 6, 29))
(80, 'Silverstone', 2025, 12, datetime.date(2025, 7, 6))
(81, 'Spa-Francorchamps', 2025, 13, datetime.date(2025, 7, 27))
(82, 'Budapest', 2025, 14, datetime.date(2025, 8, 3))
(83, 'Zandvoort', 2025, 15, datetime.date(2025, 8, 31))
(84, 'Monza', 2025, 16, datetime.date(2025, 9, 7))
(85, 'Baku', 2025, 17, datetime.date(2025, 9, 21))
(86, 'Marina Bay', 2025, 18, datetime.date(2025, 10, 5))
(87, 'Austin', 2025, 19, datetime.date(2025, 10, 19))
(88, 'Mexico City', 2025, 20, datetime.date(2025, 10, 26))
(89, 'São Paulo', 2025, 21, datetime.date(2025, 11, 9))
(90, 'Las Vegas', 2025, 22, datetime.date(2025, 11, 22))
(91, 'Lusail', 2025, 23, datetime.date(2025, 11, 30))
(92, 'Yas Island', 2025, 24, datetime.date(2025, 12, 7))

In [4]:
import fastf1

In [5]:
ff1_race = fastf1.get_session(2023, 1, 'R')

req         WARNING 	DEFAULT CACHE ENABLED! (6.4 GB) /home/lukam/.cache/fastf1

In [6]:
ff1_race.load()

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '55', '44', '18', '63', '77', '10', '23', '22', '2', '20', '21', '27', '24', '4', '31', '16', '81']

In [7]:
laps = ff1_race.laps
laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:04:15.902000,VER,1,0 days 00:01:39.019000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:42.414000,...,False,Red Bull Racing,0 days 01:02:36.652000,2023-03-05 15:03:38.501,12,1.0,False,,False,False
1,0 days 01:05:53.876000,VER,1,0 days 00:01:37.974000,2.0,1.0,NaT,NaT,0 days 00:00:31.342000,0 days 00:00:42.504000,...,False,Red Bull Racing,0 days 01:04:15.902000,2023-03-05 15:05:17.751,12,1.0,False,,False,True
2,0 days 01:07:31.882000,VER,1,0 days 00:01:38.006000,3.0,1.0,NaT,NaT,0 days 00:00:31.388000,0 days 00:00:42.469000,...,False,Red Bull Racing,0 days 01:05:53.876000,2023-03-05 15:06:55.725,1,1.0,False,,False,True
3,0 days 01:09:09.858000,VER,1,0 days 00:01:37.976000,4.0,1.0,NaT,NaT,0 days 00:00:31.271000,0 days 00:00:42.642000,...,False,Red Bull Racing,0 days 01:07:31.882000,2023-03-05 15:08:33.731,1,1.0,False,,False,True
4,0 days 01:10:47.893000,VER,1,0 days 00:01:38.035000,5.0,1.0,NaT,NaT,0 days 00:00:31.244000,0 days 00:00:42.724000,...,False,Red Bull Racing,0 days 01:09:09.858000,2023-03-05 15:10:11.707,1,1.0,False,,False,True

In [8]:
ver_laps = laps[laps['Driver'] == 'VER'].copy()
ver_laps['prev_position'] = ver_laps['Position'].shift(1)
ver_laps[['LapNumber', 'Position', 'prev_position', 'PitInTime']].head(20)

    LapNumber  Position  prev_position              PitInTime
0         1.0       1.0            NaN                    NaT
1         2.0       1.0            1.0                    NaT
2         3.0       1.0            1.0                    NaT
3         4.0       1.0            1.0                    NaT
4         5.0       1.0            1.0                    NaT
5         6.0       1.0            1.0                    NaT
6         7.0       1.0            1.0                    NaT
7         8.0       1.0            1.0                    NaT
8         9.0       1.0            1.0                    NaT
9        10.0       1.0            1.0                    NaT
10       11.0       1.0            1.0                    NaT
11       12.0       1.0            1.0                    NaT
12       13.0       1.0            1.0                    NaT
13       14.0       1.0            1.0 0 days 01:25:33.830000
14       15.0       2.0            1.0                    NaT
15       16.0       2.0            2.0                    NaT
16       17.0       2.0            2.0                    NaT
17       18.0       1.0            2.0                    NaT
18       19.0       1.0            1.0                    NaT
19       20.0       1.0            1.0                    NaT

In [9]:
ver_laps['is_overtake'] = (ver_laps['Position'] < ver_laps['prev_position']) & (ver_laps['PitInTime'].isna()) & laps['PitOutTime'].isna()

In [10]:
ver_laps[ver_laps['is_overtake'] == True][['LapNumber', 'Position', 'prev_position', 'PitInTime']]

    LapNumber  Position  prev_position PitInTime
17       18.0       1.0            2.0       NaT

In [11]:
ver_laps['is_overtake'].sum()

np.int64(1)

In [12]:
laps['prev_position'] = laps.groupby('Driver')['Position'].transform(lambda x: x.shift(1))
laps['is_overtake'] = (laps['Position'] < laps['prev_position']) & (laps['PitInTime'].isna()) & laps['PitOutTime'].isna()

In [13]:
laps.groupby('Driver')['is_overtake'].sum()

Driver
ALB     7
ALO     9
BOT     7
DEV    12
GAS    11
HAM     6
HUL     6
LEC     3
MAG    11
NOR     8
OCO     7
PER     3
PIA     2
RUS     5
SAI     4
SAR     8
STR     6
TSU    10
VER     1
ZHO    11
Name: is_overtake, dtype: int64

In [14]:
laps['is_overtake'].sum()

np.int64(137)

In [15]:
laps.groupby('Driver')['is_overtake'].sum()

Driver
ALB     7
ALO     9
BOT     7
DEV    12
GAS    11
HAM     6
HUL     6
LEC     3
MAG    11
NOR     8
OCO     7
PER     3
PIA     2
RUS     5
SAI     4
SAR     8
STR     6
TSU    10
VER     1
ZHO    11
Name: is_overtake, dtype: int64

In [16]:
laps['prev_position'] = laps.groupby('Driver')['Position'].transform(lambda x: x.shift(1))
laps['is_overtake'] = (laps['Position'] < laps['prev_position']) & (laps['PitInTime'].isna()) & (laps['PitOutTime'].isna())
laps['is_overtake'].sum()

np.int64(137)

In [17]:
laps[laps['PitOutTime'].notna()][['Driver', 'LapNumber', 'Position', 'prev_position', 'is_overtake', 'PitOutTime']].head(20)

,Driver,LapNumber,Position,prev_position,is_overtake,PitOutTime
14,VER,15.0,2.0,1.0,False,0 days 01:25:58.127000
36,VER,37.0,1.0,1.0,False,0 days 02:02:10.556000
66,GAS,10.0,20.0,19.0,False,0 days 01:18:21.104000
82,GAS,26.0,17.0,12.0,False,0 days 01:45:11.481000
97,GAS,41.0,10.0,10.0,False,0 days 02:10:15.719000
131,PER,18.0,3.0,1.0,False,0 days 01:31:05.324000
148,PER,35.0,2.0,2.0,False,0 days 01:59:08.856000
185,ALO,15.0,8.0,4.0,False,0 days 01:26:27.142000
205,ALO,35.0,6.0,3.0,False,0 days 01:59:32.653000
241,LEC,14.0,5.0,3.0,False,0 days 01:24:29.253000
261,LEC,34.0,4.0,3.0,False,0 days 01:57:39.468000
283,STR,16.0,9.0,4.0,False,0 days 01:28:09.343000
298,STR,31.0,8.0,8.0,False,0 days 01:53:09.128000
337,SAR,13.0,15.0,10.0,False,0 days 01:23:19.958000
355,SAR,31.0,14.0,10.0,False,0 days 01:53:33.675000
365,SAR,41.0,14.0,12.0,False,0 days 02:10:29.016000
396,MAG,16.0,18.0,11.0,False,0 days 01:28:34.186000
410,MAG,30.0,17.0,13.0,False,0 days 01:52:04.754000
421,MAG,41.0,15.0,15.0,False,0 days 02:10:44.250000
448,DEV,12.0,19.0,17.0,False,0 days 01:21:45.569000

In [18]:
laps['TrackStatus'].value_counts()

TrackStatus
1       979
12       26
21       19
126      14
671      13
2671      5
Name: count, dtype: int64

In [19]:
green_flag_laps = laps[laps['TrackStatus'] == '1']
green_flag_laps['is_overtake'].sum()

np.int64(124)

In [20]:
green_flag_laps.groupby('Driver')['is_overtake'].sum()

Driver
ALB     7
ALO     8
BOT     6
DEV    10
GAS    10
HAM     5
HUL     6
LEC     3
MAG    11
NOR     7
OCO     6
PER     3
PIA     2
RUS     4
SAI     3
SAR     8
STR     5
TSU    10
VER     1
ZHO     9
Name: is_overtake, dtype: int64

In [21]:
green_flag_laps.groupby('Driver')['is_overtake'].sum().sort_values(ascending=False)

Driver
MAG    11
DEV    10
GAS    10
TSU    10
ZHO     9
SAR     8
ALO     8
ALB     7
NOR     7
BOT     6
OCO     6
HUL     6
HAM     5
STR     5
RUS     4
LEC     3
PER     3
SAI     3
PIA     2
VER     1
Name: is_overtake, dtype: int64

In [22]:
inspector = sa.inspect(engine)
print(inspector.get_table_names())

['circuits', 'races', 'race_results', 'drivers', 'constructors', 'qualifying_results', 'weather', 'tyre_stints']

In [23]:
races_list = pd.read_sql('SELECT season, round, race_id FROM races', engine)

In [24]:
races_list.head()

   season  round  race_id
0    2022      1        1
1    2022      2        2
2    2022      3        3
3    2022      4        4
4    2022      5        5

In [25]:
for idx, row in races_list.iterrows():
    print(row['season'], row['round'], row['race_id'])

2022 1 1
2022 2 2
2022 3 3
2022 4 4
2022 5 5
2022 6 6
2022 7 7
2022 8 8
2022 9 9
2022 10 10
2022 11 11
2022 12 12
2022 13 13
2022 14 14
2022 15 15
2022 16 16
2022 17 17
2022 18 18
2022 19 19
2022 20 20
2022 21 21
2022 22 22
2023 1 23
2023 2 24
2023 3 25
2023 4 26
2023 5 27
2023 6 28
2023 7 29
2023 8 30
2023 9 31
2023 10 32
2023 11 33
2023 12 34
2023 13 35
2023 14 36
2023 15 37
2023 16 38
2023 17 39
2023 18 40
2023 19 41
2023 20 42
2023 21 43
2023 22 44
2024 1 45
2024 2 46
2024 3 47
2024 4 48
2024 5 49
2024 6 50
2024 7 51
2024 8 52
2024 9 53
2024 10 54
2024 11 55
2024 12 56
2024 13 57
2024 14 58
2024 15 59
2024 16 60
2024 17 61
2024 18 62
2024 19 63
2024 20 64
2024 21 65
2024 22 66
2024 23 67
2024 24 68
2025 1 69
2025 2 70
2025 3 71
2025 4 72
2025 5 73
2025 6 74
2025 7 75
2025 8 76
2025 9 77
2025 10 78
2025 11 79
2025 12 80
2025 13 81
2025 14 82
2025 15 83
2025 16 84
2025 17 85
2025 18 86
2025 19 87
2025 20 88
2025 21 89
2025 22 90
2025 23 91
2025 24 92

In [26]:
results = []
overtakes_df = pd.DataFrame(columns=['race_id', 'driver', 'overtake_count'])

In [27]:
import time

fastf1.Cache.enable_cache('../data/cache')
fastf1.set_log_level('ERROR')

completed_race_ids = set(overtakes_df['race_id'].unique())

for idx, row in races_list.iterrows():
    if row['race_id'] in completed_race_ids:
        continue
    
    try:
        session = fastf1.get_session(row['season'], row['round'], 'R')
        session.load(messages=False, weather=False)
        
        laps = session.laps
        laps = laps[laps['TrackStatus'] == '1'].copy()
        
        laps['prev_position'] = laps.groupby('Driver')['Position'].transform(lambda x: x.shift(1))
        laps['is_overtake'] = (laps['Position'] < laps['prev_position']) & (laps['PitInTime'].isna()) & (laps['PitOutTime'].isna())
        
        driver_overtakes = laps.groupby('Driver')['is_overtake'].sum()
        
        for driver, count in driver_overtakes.items():
            results.append({'race_id': row['race_id'], 'driver': driver, 'overtake_count': count})
        
        completed_race_ids.add(row['race_id'])
        print(f"Done {row['season']} R{row['round']}")
        time.sleep(15)
        
    except Exception as e:
        print(f"Failed {row['season']} R{row['round']}: {e}")
        time.sleep(60)

overtakes_df = pd.DataFrame(results)
print(overtakes_df['race_id'].nunique(), "races completed")

Done 2022 R1
Done 2022 R2
Done 2022 R3
Done 2022 R4
Done 2022 R5
Done 2022 R6
Done 2022 R7
Done 2022 R8
Done 2022 R9
Done 2022 R10
Done 2022 R11
Done 2022 R12
Done 2022 R13
Done 2022 R14
Done 2022 R15
Done 2022 R16
Done 2022 R17
Done 2022 R18
Done 2022 R19
Done 2022 R20
Done 2022 R21
Done 2022 R22
Done 2023 R1
Done 2023 R2
Done 2023 R3
Done 2023 R4
Done 2023 R5
Done 2023 R6
Done 2023 R7
Done 2023 R8
Done 2023 R9
Done 2023 R10
Done 2023 R11
Done 2023 R12
Done 2023 R13
Done 2023 R14
Done 2023 R15
Done 2023 R16
Done 2023 R17
Done 2023 R18
Done 2023 R19
Done 2023 R20
Done 2023 R21
Done 2023 R22
Done 2024 R1
Done 2024 R2
Done 2024 R3
Done 2024 R4
Done 2024 R5
Done 2024 R6
Done 2024 R7
Done 2024 R8
Done 2024 R9
Done 2024 R10
Done 2024 R11
Done 2024 R12
Done 2024 R13
Done 2024 R14
Done 2024 R15
Done 2024 R16
Done 2024 R17
Done 2024 R18
Done 2024 R19
Done 2024 R20
Done 2024 R21
Done 2024 R22
Done 2024 R23
Done 2024 R24
Done 2025 R1
Done 2025 R2
Done 2025 R3
Done 2025 R4
Done 2025 R5
Done 2025 R6
Done 2025 R7
Done 2025 R8
Done 2025 R9
Done 2025 R10
Done 2025 R11
Done 2025 R12
Done 2025 R13
Done 2025 R14
Done 2025 R15
Done 2025 R16
Done 2025 R17
Done 2025 R18
Done 2025 R19
Done 2025 R20
Done 2025 R21
Done 2025 R22
Done 2025 R23
Done 2025 R24
92 races completed

In [29]:
print(overtakes_df.shape)
print(overtakes_df['race_id'].nunique())
overtakes_df.head(10)

(1780, 3)
92

   race_id driver  overtake_count
0        1    ALB               8
1        1    ALO               8
2        1    BOT              16
3        1    GAS               5
4        1    HAM               7
5        1    HUL               8
6        1    LAT               9
7        1    LEC               1
8        1    MAG               6
9        1    MSC              10

In [30]:
overtakes_df = overtakes_df.sort_values(['driver', 'race_id']).reset_index(drop=True)
overtakes_df['driver_avg_overtakes'] = overtakes_df.groupby('driver')['overtake_count'].transform(lambda x: x.shift(1).expanding().mean())

In [31]:
print(overtakes_df.shape)
overtakes_df.head(20)

(1780, 4)

    race_id driver  overtake_count  driver_avg_overtakes
0         1    ALB               8                   NaN
1         2    ALB               5              8.000000
2         3    ALB               9              6.500000
3         4    ALB               3              7.333333
4         5    ALB               9              6.250000
5         6    ALB               6              6.800000
6         7    ALB               3              6.666667
7         8    ALB               5              6.142857
8         9    ALB               6              6.000000
9        11    ALB              10              6.000000
10       12    ALB               2              6.400000
11       13    ALB              10              6.000000
12       14    ALB              12              6.333333
13       15    ALB              12              6.769231
14       17    ALB               2              7.142857
15       19    ALB               7              6.800000
16       20    ALB              10              6.812500
17       21    ALB               9              7.000000
18       22    ALB              12              7.111111
19       23    ALB               7              7.368421

In [32]:
# check database driver ids
pd.read_sql("SELECT DISTINCT driver_id FROM race_results LIMIT 20", engine)

          driver_id
0             gasly
1            norris
2         colapinto
3            bottas
4           piastri
5            vettel
6         ricciardo
7         bortoleto
8            lawson
9          sargeant
10           stroll
11   max_verstappen
12          tsunoda
13          russell
14             ocon
15  kevin_magnussen
16  mick_schumacher
17         hamilton
18         de_vries
19       hulkenberg

In [33]:
driver_map = {
    'ALB': 'albon',
    'ALO': 'alonso',
    'BOT': 'bottas',
    'COL': 'colapinto',
    'DEV': 'de_vries',
    'GAS': 'gasly',
    'HAM': 'hamilton',
    'HUL': 'hulkenberg',
    'LAT': 'latifi',
    'LAW': 'lawson',
    'LEC': 'leclerc',
    'MAG': 'kevin_magnussen',
    'MSC': 'mick_schumacher',
    'NOR': 'norris',
    'OCO': 'ocon',
    'PER': 'perez',
    'PIA': 'piastri',
    'RIC': 'ricciardo',
    'RUS': 'russell',
    'SAI': 'sainz',
    'SAR': 'sargeant',
    'STR': 'stroll',
    'TSU': 'tsunoda',
    'VER': 'max_verstappen',
    'VET': 'vettel',
    'ZHO': 'zhou',
    'ANT': 'antonelli',
    'BEA': 'bearman',
    'BOR': 'bortoleto',
    'DOO': 'doohan',
    'HAD': 'hadjar',
}

In [34]:
overtakes_df['driver_id'] = overtakes_df['driver'].map(driver_map)

In [35]:
print(overtakes_df['driver_id'].isna().sum())
overtakes_df[overtakes_df['driver_id'].isna()]['driver'].unique()

0

array([], dtype=object)

In [36]:
grid_df = pd.read_sql("SELECT race_id, driver_id, grid_position FROM race_results", engine)
overtakes_df = overtakes_df.merge(grid_df, on=['race_id', 'driver_id'], how='left')
print(overtakes_df.shape)
overtakes_df.head()

(1780, 6)

,race_id,driver,overtake_count,driver_avg_overtakes,driver_id,grid_position
0,1,ALB,8,NaN,albon,14.0
1,2,ALB,5,8.000000,albon,16.0
2,3,ALB,9,6.500000,albon,20.0
3,4,ALB,3,7.333333,albon,18.0
4,5,ALB,9,6.250000,albon,18.0

In [37]:
overtakes_df[['overtake_count', 'driver_avg_overtakes', 'grid_position']].isnull().sum()

overtake_count           0
driver_avg_overtakes    31
grid_position            0
dtype: int64

In [38]:
model_df = overtakes_df.dropna(subset=['driver_avg_overtakes']).copy()
print(model_df.shape)

(1749, 6)

In [39]:
seasons_df = pd.read_sql("SELECT race_id, season FROM races", engine)
model_df = model_df.merge(seasons_df, on='race_id', how='left')

train_df = model_df[model_df['season'] < 2025].copy()
test_df = model_df[model_df['season'] == 2025].copy()

print(train_df.shape, test_df.shape)

(1291, 7) (458, 7)

In [40]:
import xgboost as xgb

features = ['grid_position', 'driver_avg_overtakes']

X_train = train_df[features]
X_test = test_df[features]
y_train = train_df['overtake_count']
y_test = test_df['overtake_count']

dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

params = {
    'objective': 'count:poisson',
    'eval_metric': 'poisson-nloglik',
    'eta': 0.05,
    'max_depth': 4,
    'min_child_weight': 5,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
}

bst = xgb.train(
    params,
    dtrain,
    num_boost_round=500,
    evals=[(dtrain, 'train'), (dtest, 'test')],
    early_stopping_rounds=40,
    verbose_eval=20
)

print("Best iteration:", bst.best_iteration)
print("Best test score:", bst.best_score)

[0]	train-poisson-nloglik:3.05363	test-poisson-nloglik:2.97809
[20]	train-poisson-nloglik:2.96325	test-poisson-nloglik:2.91099
[40]	train-poisson-nloglik:2.90900	test-poisson-nloglik:2.87185
[60]	train-poisson-nloglik:2.88337	test-poisson-nloglik:2.86094
[80]	train-poisson-nloglik:2.85481	test-poisson-nloglik:2.83965
[100]	train-poisson-nloglik:2.83431	test-poisson-nloglik:2.82875
[120]	train-poisson-nloglik:2.81938	test-poisson-nloglik:2.82172
[140]	train-poisson-nloglik:2.80714	test-poisson-nloglik:2.81579
[160]	train-poisson-nloglik:2.79743	test-poisson-nloglik:2.81448
[180]	train-poisson-nloglik:2.78970	test-poisson-nloglik:2.81505
[200]	train-poisson-nloglik:2.78168	test-poisson-nloglik:2.81535
[202]	train-poisson-nloglik:2.78109	test-poisson-nloglik:2.81651
Best iteration: 162
Best test score: 2.8140571101784184

In [41]:
import numpy as np

preds = bst.predict(dtest)
test_df['predicted_overtakes'] = preds

mae = np.abs(test_df['overtake_count'] - test_df['predicted_overtakes']).mean()
print(f"Mean absolute error: {mae:.2f} overtakes")

# also look at actual vs predicted distribution
print(f"\nActual overtakes - mean: {test_df['overtake_count'].mean():.2f}, std: {test_df['overtake_count'].std():.2f}")
print(f"Predicted overtakes - mean: {test_df['predicted_overtakes'].mean():.2f}, std: {test_df['predicted_overtakes'].std():.2f}")

Mean absolute error: 2.90 overtakes

Actual overtakes - mean: 6.17, std: 3.85
Predicted overtakes - mean: 6.23, std: 1.34

In [42]:
baseline_pred = y_train.mean()
baseline_mae = np.abs(test_df['overtake_count'] - baseline_pred).mean()
print(f"Baseline MAE (predict mean always): {baseline_mae:.2f} overtakes")

Baseline MAE (predict mean always): 3.15 overtakes

In [43]:
test_df[['driver_id', 'race_id', 'grid_position', 'driver_avg_overtakes', 'overtake_count', 'predicted_overtakes']].sort_values('race_id').head(20)

,driver_id,race_id,grid_position,driver_avg_overtakes,overtake_count,predicted_overtakes
60,albon,69,6.0,7.131148,1,5.829934
199,bearman,69,20.0,6.333333,2,7.769747
1551,tsunoda,69,5.0,6.500000,2,5.072728
1466,stroll,69,13.0,7.515152,3,7.468650
1125,piastri,69,2.0,5.630435,5,4.183217
1258,russell,69,4.0,5.895522,1,5.262821
412,gasly,69,9.0,7.060606,1,6.566242
521,hamilton,69,8.0,6.200000,2,6.079480
645,lawson,69,18.0,7.272727,3,6.777246
151,alonso,69,12.0,6.073529,0,7.926274
1641,max_verstappen,69,3.0,3.720588,1,4.777380
591,hulkenberg,69,17.0,6.808511,3,7.567145
992,ocon,69,19.0,6.861538,2,7.759960
733,leclerc,69,7.0,4.757576,2,5.886677
904,norris,69,1.0,5.537313,1,2.625794
61,albon,70,10.0,7.032258,10,6.456691
1467,stroll,70,14.0,7.447761,9,7.575514
993,ocon,70,11.0,6.787879,9,7.150397
1126,piastri,70,1.0,5.617021,2,3.013748
152,alonso,70,13.0,5.985507,0,6.939978

In [44]:
test_df['predicted_rounded'] = test_df['predicted_overtakes'].round()
exact_match = (test_df['predicted_rounded'] == test_df['overtake_count']).sum()
total = len(test_df)
print(f"Exact match: {exact_match}/{total} ({exact_match/total*100:.1f}%)")

Exact match: 58/458 (12.7%)

In [45]:
within_2 = (np.abs(test_df['predicted_rounded'] - test_df['overtake_count']) <= 2).sum()
print(f"Within 2 overtakes: {within_2}/{total} ({within_2/total*100:.1f}%)")

Within 2 overtakes: 234/458 (51.1%)

In [46]:
baseline_rounded = round(y_train.mean())
baseline_exact = (test_df['overtake_count'] == baseline_rounded).sum()
print(f"Baseline exact match: {baseline_exact}/{total} ({baseline_exact/total*100:.1f}%)")

Baseline exact match: 33/458 (7.2%)

In [47]:
# get constructor avg from database
constructor_df = pd.read_sql("SELECT race_id, driver_id, constructor_id FROM race_results", engine)
constructor_stats = pd.read_sql("""
    SELECT rr.race_id, rr.driver_id, 
           AVG(rr.finish_position) OVER (
               PARTITION BY rr.constructor_id 
               ORDER BY r.date
               ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
           ) as constructor_career_avg
    FROM race_results rr
    JOIN races r ON rr.race_id = r.race_id
""", engine)

model_df2 = model_df.merge(constructor_stats, on=['race_id', 'driver_id'], how='left')

# train/test split
train_df2 = model_df2[model_df2['season'] < 2025].copy()
test_df2 = model_df2[model_df2['season'] == 2025].copy()

features2 = ['grid_position', 'driver_avg_overtakes', 'constructor_career_avg']

X_train2 = train_df2[features2].fillna(train_df2[features2].mean())
X_test2 = test_df2[features2].fillna(test_df2[features2].mean())

dtrain2 = xgb.DMatrix(X_train2, label=train_df2['overtake_count'])
dtest2 = xgb.DMatrix(X_test2, label=test_df2['overtake_count'])

bst2 = xgb.train(
    params,
    dtrain2,
    num_boost_round=500,
    evals=[(dtrain2, 'train'), (dtest2, 'test')],
    early_stopping_rounds=40,
    verbose_eval=20
)

preds2 = bst2.predict(dtest2)
test_df2['predicted_overtakes'] = preds2
test_df2['predicted_rounded'] = test_df2['predicted_overtakes'].round()

exact2 = (test_df2['predicted_rounded'] == test_df2['overtake_count']).sum()
within2 = (np.abs(test_df2['predicted_rounded'] - test_df2['overtake_count']) <= 2).sum()
total2 = len(test_df2)

print(f"Exact match: {exact2}/{total2} ({exact2/total2*100:.1f}%)")
print(f"Within 2: {within2}/{total2} ({within2/total2*100:.1f}%)")

[0]	train-poisson-nloglik:3.05242	test-poisson-nloglik:2.97894
[20]	train-poisson-nloglik:2.91353	test-poisson-nloglik:2.88696
[40]	train-poisson-nloglik:2.84157	test-poisson-nloglik:2.84710
[60]	train-poisson-nloglik:2.78794	test-poisson-nloglik:2.82565
[80]	train-poisson-nloglik:2.75326	test-poisson-nloglik:2.81588
[100]	train-poisson-nloglik:2.72197	test-poisson-nloglik:2.81242
[120]	train-poisson-nloglik:2.69851	test-poisson-nloglik:2.81139
[140]	train-poisson-nloglik:2.67600	test-poisson-nloglik:2.81372
[151]	train-poisson-nloglik:2.66373	test-poisson-nloglik:2.81705
Exact match: 50/458 (10.9%)
Within 2: 237/458 (51.7%)

In [ ]:
print(model_df3.columns.tolist())