In [17]:
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

load_dotenv('../.env')

engine = create_engine(
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

# Test connection
df = pd.read_sql("SELECT COUNT(*) as total_results FROM race_results", engine)
print(df)

   total_results
0            460

In [18]:
query = """
SELECT 
    rr.driver_id,
    rr.constructor_id,
    rr.grid_position,
    rr.finish_position,
    rr.points,
    rr.points_finish,
    rr.status,
    r.season,
    r.round,
    r.circuit_id,
    r.date,
    q.q1_time,
    q.q2_time,
    q.q3_time,
    w.air_temp,
    w.track_temp,
    w.rainfall,
    w.humidity
FROM race_results rr
JOIN races r ON rr.race_id = r.race_id
LEFT JOIN qualifying_results q ON q.race_id = rr.race_id AND q.driver_id = rr.driver_id
LEFT JOIN weather w ON w.race_id = rr.race_id
ORDER BY r.date, rr.finish_position
"""

df = pd.read_sql(query, engine)
print(df.shape)
df.head(10)

(460, 18)

,driver_id,constructor_id,grid_position,finish_position,points,points_finish,status,season,round,circuit_id,date,q1_time,q2_time,q3_time,air_temp,track_temp,rainfall,humidity
0,max_verstappen,red_bull,1.0,1.0,25.0,True,Finished,2023,1,Sakhir,2023-03-05,91.295,90.503,89.708,27.431677,31.011801,False,21.496894
1,perez,red_bull,2.0,2.0,18.0,True,Finished,2023,1,Sakhir,2023-03-05,91.479,90.746,89.846,27.431677,31.011801,False,21.496894
2,alonso,aston_martin,5.0,3.0,15.0,True,Finished,2023,1,Sakhir,2023-03-05,91.158,90.645,90.336,27.431677,31.011801,False,21.496894
3,sainz,ferrari,4.0,4.0,12.0,True,Finished,2023,1,Sakhir,2023-03-05,90.993,90.515,90.154,27.431677,31.011801,False,21.496894
4,hamilton,mercedes,7.0,5.0,10.0,True,Finished,2023,1,Sakhir,2023-03-05,91.543,90.513,90.384,27.431677,31.011801,False,21.496894
5,stroll,aston_martin,8.0,6.0,8.0,True,Finished,2023,1,Sakhir,2023-03-05,91.184,91.127,90.836,27.431677,31.011801,False,21.496894
6,russell,mercedes,6.0,7.0,6.0,True,Finished,2023,1,Sakhir,2023-03-05,91.057,90.507,90.340,27.431677,31.011801,False,21.496894
7,bottas,alfa,12.0,8.0,4.0,True,Finished,2023,1,Sakhir,2023-03-05,91.504,91.443,NaN,27.431677,31.011801,False,21.496894
8,gasly,alpine,20.0,9.0,2.0,True,Finished,2023,1,Sakhir,2023-03-05,92.181,NaN,NaN,27.431677,31.011801,False,21.496894
9,albon,williams,15.0,10.0,1.0,True,Finished,2023,1,Sakhir,2023-03-05,91.461,NaN,NaN,27.431677,31.011801,False,21.496894

In [19]:
df.shape

(460, 18)

In [20]:
pd.read_sql("""
    SELECT driver_id, race_id, COUNT(*) as count 
    FROM race_results 
    GROUP BY driver_id, race_id 
    HAVING COUNT(*) > 1
    LIMIT 5
""", engine)

Empty DataFrame
Columns: [driver_id, race_id, count]
Index: []

In [21]:
df.shape

(460, 18)

In [22]:
df.head(20)

,driver_id,constructor_id,grid_position,finish_position,points,points_finish,status,season,round,circuit_id,date,q1_time,q2_time,q3_time,air_temp,track_temp,rainfall,humidity
0,max_verstappen,red_bull,1.0,1.0,25.0,True,Finished,2023,1,Sakhir,2023-03-05,91.295,90.503,89.708,27.431677,31.011801,False,21.496894
1,perez,red_bull,2.0,2.0,18.0,True,Finished,2023,1,Sakhir,2023-03-05,91.479,90.746,89.846,27.431677,31.011801,False,21.496894
2,alonso,aston_martin,5.0,3.0,15.0,True,Finished,2023,1,Sakhir,2023-03-05,91.158,90.645,90.336,27.431677,31.011801,False,21.496894
3,sainz,ferrari,4.0,4.0,12.0,True,Finished,2023,1,Sakhir,2023-03-05,90.993,90.515,90.154,27.431677,31.011801,False,21.496894
4,hamilton,mercedes,7.0,5.0,10.0,True,Finished,2023,1,Sakhir,2023-03-05,91.543,90.513,90.384,27.431677,31.011801,False,21.496894
5,stroll,aston_martin,8.0,6.0,8.0,True,Finished,2023,1,Sakhir,2023-03-05,91.184,91.127,90.836,27.431677,31.011801,False,21.496894
6,russell,mercedes,6.0,7.0,6.0,True,Finished,2023,1,Sakhir,2023-03-05,91.057,90.507,90.340,27.431677,31.011801,False,21.496894
7,bottas,alfa,12.0,8.0,4.0,True,Finished,2023,1,Sakhir,2023-03-05,91.504,91.443,NaN,27.431677,31.011801,False,21.496894
8,gasly,alpine,20.0,9.0,2.0,True,Finished,2023,1,Sakhir,2023-03-05,92.181,NaN,NaN,27.431677,31.011801,False,21.496894
9,albon,williams,15.0,10.0,1.0,True,Finished,2023,1,Sakhir,2023-03-05,91.461,NaN,NaN,27.431677,31.011801,False,21.496894
10,tsunoda,alphatauri,14.0,11.0,0.0,False,Finished,2023,1,Sakhir,2023-03-05,91.400,92.510,NaN,27.431677,31.011801,False,21.496894
11,sargeant,williams,16.0,12.0,0.0,False,Lapped,2023,1,Sakhir,2023-03-05,91.652,NaN,NaN,27.431677,31.011801,False,21.496894
12,kevin_magnussen,haas,17.0,13.0,0.0,False,Lapped,2023,1,Sakhir,2023-03-05,91.892,NaN,NaN,27.431677,31.011801,False,21.496894
13,de_vries,alphatauri,19.0,14.0,0.0,False,Lapped,2023,1,Sakhir,2023-03-05,92.121,NaN,NaN,27.431677,31.011801,False,21.496894
14,hulkenberg,haas,10.0,15.0,0.0,False,Lapped,2023,1,Sakhir,2023-03-05,91.204,90.809,NaN,27.431677,31.011801,False,21.496894
15,zhou,alfa,13.0,16.0,0.0,False,Lapped,2023,1,Sakhir,2023-03-05,91.615,91.473,NaN,27.431677,31.011801,False,21.496894
16,norris,mclaren,11.0,17.0,0.0,False,Lapped,2023,1,Sakhir,2023-03-05,91.652,91.381,NaN,27.431677,31.011801,False,21.496894
17,ocon,alpine,9.0,18.0,0.0,False,Retired,2023,1,Sakhir,2023-03-05,91.508,90.914,90.984,27.431677,31.011801,False,21.496894
18,leclerc,ferrari,3.0,19.0,0.0,False,Retired,2023,1,Sakhir,2023-03-05,91.094,90.282,90.000,27.431677,31.011801,False,21.496894
19,piastri,mclaren,18.0,20.0,0.0,False,Retired,2023,1,Sakhir,2023-03-05,92.101,NaN,NaN,27.431677,31.011801,False,21.496894

In [23]:
df,isnull().sum()

NameError: name 'isnull' is not defined

In [24]:
df.isnull().sum()

driver_id            0
constructor_id       0
grid_position        1
finish_position      1
points               0
points_finish        0
status               0
season               0
round                0
circuit_id           0
date                 0
q1_time              4
q2_time            119
q3_time            236
air_temp             0
track_temp           0
rainfall             0
humidity             0
dtype: int64